export enum RegExprComponentNames {
  //Object
  ObjectLiteral = 'Object Notation',
  ObjectConstructor = 'Object Constructor',
  //RegExpr Class
  RegExpr = 'Reg Expr',
  //RegExpr Methods
  Exec = 'Exec',
  Test = 'Test',
  //String Methods
  Match = 'Match',
  Match_All = 'Match All',
  Replace = 'Replace',
  Replace_All = 'Replace All',
  Search = 'Search',
  //Modifiers
  Start_End_Indices = 'Start End Indices',
  Global = 'Global',
  Case_Insensitive = 'Case Insensitive',
  Multi_Line_Search = 'Multi Line Search',
  Match_Newline = 'Match Newline',
  Unicode = 'Unicode',
  Sticky = 'Sticky',
  //Groups and Ranges
  Matches_Either = 'Matches Either',
  Matches_Any_One = 'Matches Any One',
  Negated = 'Negated',
  Capturing_Group = 'Capturing Group',
  //Meta Characters
  Single = 'Single',
  Word = 'Word',
  Non_Word = 'Non Word',
  Digit = 'Digit',
  Non_Digit = 'Non Digit',
  Whitespace = 'Whitespace',
  Non_Whitespace = 'Non Whitespace',
  Beginning_End_Word = 'Beginning End Word',
  Non_Beginning_End_Word = 'Non Beginning End Word',
  Null = 'Null',
  New_line = 'New line',
  Form_Feed = 'Form Feed',
  Carriage_Return = 'Carriage Return',
  Tab = 'Tab',
  Vertical_Tab = 'Vertical Tab',
  Octal_Number = 'Octal Number',
  Hexadecimal_Number = 'Hexadecimal Number',
  //Quantifiers
  At_Least_One = 'At Least One',
  Zero_Or_More = 'Zero Or More',
  Zero_Or_One = 'Zero Or One',
  Sequence_Of = 'Sequence Of',
  End = 'End',
  Beginning = 'Beginning',
  Specific_String = 'Specific String',
  Non_Specific_String = 'Non Specific String',
}
